---
- name: Copy over the mongodb backup
  copy: src=../data/envdata.tar.gz dest=/opt/envdata.tar.gz
  register: sync_backup

- name: Restore the mongodb
  shell: >
    tar -xvf /opt/envdata.tar.gz -C /tmp;
    mongorestore /tmp/envdata
  when: sync_backup.changed