---
- name: install and run the IoT dashboard project
  sudo: true
  hosts: all

  tasks:
    - name: install add-apt-repository and https binaries for Ansible to work
      apt: name={{ item }} state=present update_cache=yes
      with_items:
        - python-software-properties
        - apt-transport-https

    - name: Add NodeSource deb repository
      apt_repository:
        repo: 'deb https://deb.nodesource.com/node_4.x {{ ansible_distribution_release }} main'
        state: present

    - name: install required packages
      apt: name={{ item }} state=present force=yes
      with_items:
        - build-essential
        - libkrb5-dev
        - nodejs
        - mongodb

    - name: install node-inspector
      npm: name=node-inspector global=yes

    - name: install coffee-script
      npm: name=coffee-script global=yes

    - name: Copy over the mongodb backup
      copy: src=../data/envdata.tar.gz dest=/opt/envdata.tar.gz
      register: sync_backup

    - name: Restore the mongodb
      shell: >
        mkdir /tmp/envdata;
        tar -xvf /opt/envdata.tar.gz -C /tmp/envdata;
        mongorestore /tmp/envdata
      when: sync_backup.changed